---
output: pdf_document
geometry: margin=2cm
params:
  country: "Gambia"
---

---
title: "**`r params$country`**"
---

<style>
p.caption {
  font-size: 0.8cm;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
 fig.align="center",
 fig.width = 30,
 fig.asp = 0.5,
 out.height= "0.5\\paperheight"
)
```

```{r, include=FALSE}
rm(list=ls()[-which(ls()=="params")])
#load(paste0("~/Zimbabwe spline err P2 + P1 P2 mid hump.RData"))
#load(paste0("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/thiele spline RData/",params$country," spline RW.RData"))
load(paste0("~/",params$country," tau Gumbel P1.RData"))

library(dplyr)
library(tidyr)
library(forcats)
library(ggplot2)
library(tmbstan)
library(readr)
library(popReconstruct)
library(tidyverse)
library(TMB)
library(ggnewscale)
library(DDSQLtools)
library(ggforce)
library(stringr)
library(Matrix)
library(gridExtra)

require(devtools)
require(httr)

req <- GET("https://api.github.com/repos/sarahertog/ddharmony/git/trees/main?recursive=1")
stop_for_status(req)
filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F)

for (filename in filelist) {
  one_function <- paste0("https://github.com/sarahertog/ddharmony/blob/main/", filename, "?raw=TRUE")
  source_url(one_function)
  rm(one_function)
}
rm(req, filelist, filename)

#compile("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/ccmpp_bothsexes_thiele_loghump_oag_RW_originalscale_spline.cpp")
#dyn.load(dynlib("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/ccmpp_bothsexes_thiele_loghump_oag_RW_originalscale_spline"))
#dyn.load(dynlib("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/ccmpp_bothsexes_thiele_loghump_oag_RW_originalscale_spline_RW_aggr_ARIMA"))
dyn.load(dynlib("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/ccmpp_bothsexes_thiele_loghump_oag_RW_originalscale_spline_RW_aggr_gumbel"))

projection_indices <- function(period_start,  period_end, interval, n_ages,
                               fx_idx, n_fx, n_sexes = 1) {
  
  stopifnot(n_sexes %in% 1:2)
  
  periods_out <- seq(period_start, period_end + interval, by = interval)
  periods <- periods_out[-length(periods_out)]
  ages <- 0:(n_ages - 1) * interval
  fertility_ages <- ages[fx_idx + 0:(n_fx - 1L)]
  sexes <- if(n_sexes == 1) "female" else c("female", "male")
  
  list(periods = periods,
       periods_out = periods_out,
       ages = ages,
       fertility_ages = fertility_ages,
       sexes = sexes,
       interval = interval,
       n_periods = length(periods),
       n_ages = n_ages,
       fx_idx = fx_idx,
       n_fx = n_fx,
       n_sexes = n_sexes)
}
projection_model_frames <- function(indices) {
  
  mf_population <- tidyr::crossing(period = indices$periods_out,
                                   sex = indices$sexes,
                                   age = indices$ages)
  
  mf_deaths <- tidyr::crossing(period = indices$periods,
                               sex = indices$sexes,
                               age = indices$ages)
  
  cohort_death_ages <- c(indices$ages, max(indices$ages) + indices$interval)
  mf_cohort_deaths <- tidyr::crossing(period = indices$periods,
                                      sex = indices$sexes,
                                      age = cohort_death_ages)
  
  mf_migrations <- tidyr::crossing(period = indices$periods,
                                   sex = indices$sexes,
                                   age = indices$ages)
  
  mf_births <- tidyr::crossing(period = indices$periods,
                               age = indices$fertility_ages)
  
  list(mf_population = mf_population,
       mf_deaths = mf_deaths,
       mf_cohort_deaths = mf_cohort_deaths,
       mf_migrations = mf_migrations,
       mf_births = mf_births)
}

proj_to_long <- function(proj, mf, value_col = "value") {
  
  val <- list()
  val$population <- mf$mf_population
  val$population[[value_col]] <- as.vector(proj$population)
  
  val$population <- mf$mf_cohort_deaths
  val$population[[value_col]] <- as.vector(proj$cohort_deathsg)
  
}

make_tmb_obj <- function(data,
                         par,
                         model = "ccmpp_tmb",
                         inner_verbose = FALSE,
                         calc_outputs = TRUE,
                         random,
                         DLL = "leapfrog_TMBExports",
                         map = list()) {
  
  data$model <- model
  data$calc_outputs <- as.integer(calc_outputs)
  
  obj <- TMB::MakeADFun(data = data,
                        parameters = par,
                        DLL = DLL,
                        silent = !inner_verbose,
                        random = random,
                        map = map)
  class(obj) <- "tmb_obj"
  
  obj
}

fit_tmb <- function(tmb_input,
                    outer_verbose = TRUE,
                    inner_verbose = FALSE,
                    max_iter = 250,
                    random,
                    DLL = "leapfrog_TMBExports",
                    map = list(),
                    stepmin = 1,
                    stepmax = 1
) {
  
  ## stopifnot(inherits(tmb_input, "tmb_input"))
  
  if(is.null(tmb_input$model))
    tmb_input$model <- "ccmpp_tmb"
  
  obj <- make_tmb_obj(data = tmb_input$data,
                      par = tmb_input$par_init,
                      model = tmb_input$model,
                      inner_verbose = inner_verbose,
                      calc_outputs = 0L,
                      random = random,
                      DLL = DLL,
                      map = map)
  
  trace <- if(outer_verbose) 1 else 0
  f <- withCallingHandlers(
    stats::nlminb(obj$par, obj$fn, obj$gr,
                  control = list(trace = trace,
                                 iter.max = max_iter,
                                 step.min = stepmin,
                                 step.max = stepmax)),
    warning = function(w) {
      if(grepl("NA/NaN function evaluation", w$message))
        invokeRestart("muffleWarning")
    }
  )
  
  if(f$convergence != 0)
    warning(paste("convergence error:", f$message))
  
  if(outer_verbose)
    message(paste("converged:", f$message))
  
  f$par.fixed <- f$par
  f$par.full <- obj$env$last.par
  
  objout <- make_tmb_obj(tmb_input$data,
                         tmb_input$par_init,
                         model = tmb_input$model,
                         inner_verbose = inner_verbose,
                         calc_outputs = 1L,
                         DLL = DLL,
                         map = map,
                         random = random)
  f$mode <- objout$report(f$par.full)
  
  val <- c(f, obj = list(objout))
  class(val) <- "leapfrog_fit"
  
  val
}

igme.5q0.m<-read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/5q0 male.csv")
igme.5q0.f<-read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/5q0 female.csv")
wpp.fx <- read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/WPP fx.csv")
wpp.pop <- read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/WPP Pop estimates.csv")
wpp.pop.age.specific <- read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/WPP pop age specific.csv")
wpp.q4515 <- read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/WPP 45q15.csv")
gbd.q4515 <- read.csv(file="C:/Users/ktang3/Desktop/Imperial/SSA_mort/GBD 45q15.csv",header=T)
wpp.qx <- read.csv("C:/Users/ktang3/Desktop/Imperial/Pop_Construct/WPP age specific.csv")

gbd.q4515$location_name<-str_replace(gbd.q4515$location_name,"Democratic Republic of the Congo","Congo Democratic Republic")
gbd.q4515$location_name<-str_replace(gbd.q4515$location_name,"Côte d'Ivoire","Cote d'Ivoire")
gbd.q4515$location_name<-str_replace(gbd.q4515$location_name,"United Republic of Tanzania","Tanzania")

igme.5q0.m$Country.Name <- str_replace(igme.5q0.m$Country.Name,"Democratic Republic of the Congo","Congo Democratic Republic")
igme.5q0.f$Country.Name <- str_replace(igme.5q0.f$Country.Name,"Democratic Republic of the Congo","Congo Democratic Republic")
igme.5q0.m$Country.Name<-str_replace(igme.5q0.m$Country.Name,"United Republic of Tanzania","Tanzania")
igme.5q0.f$Country.Name<-str_replace(igme.5q0.f$Country.Name,"United Republic of Tanzania","Tanzania")

wpp.qx$name <- str_replace(wpp.qx$name,"Democratic Republic of the Congo","Congo Democratic Republic")
wpp.qx$name <- str_replace(wpp.qx$name,"Democratic Republic of the Congo","Congo Democratic Republic")
wpp.qx$name<-str_replace(wpp.qx$name,"United Republic of Tanzania","Tanzania")
wpp.qx$name<-str_replace(wpp.qx$name,"United Republic of Tanzania","Tanzania")

open.age <- 85
n_ages <- open.age + 1
interval <- 1 #just in case

country <- params$country

library(MortCast)
load("~/cohort smooth 1900-2017.RData")
LQcoef.f <- LQcoef %>% filter(sex=="Female", !age%in%c("0","1-4")) %>% select(ax:vx)
LQcoef.m <- LQcoef %>% filter(sex=="Male", !age%in%c("0","1-4")) %>% select(ax:vx)

##IGME 5q0
igme.5q0.df <- igme.5q0.f %>% filter(Country.Name == country) %>% reshape2::melt() %>% 
  mutate(year = as.numeric(gsub("X|\\.5","",variable)), child.mort = value/1000, Sex = "Female") %>%
  select(year,child.mort, Sex) %>%
  bind_rows(
    igme.5q0.m %>% filter(Country.Name == country) %>% reshape2::melt() %>% 
      mutate(year = as.numeric(gsub("X|\\.5","",variable)), child.mort = value/1000, Sex = "Male") %>%
      select(year,child.mort, Sex)
  )


#WPP 5q0
wpp.bf.qx <- wpp.qx %>% filter(name==country, Sex!="Total")

wpp.5q0 <- wpp.bf.qx %>% filter(AgeGrpStart %in% 0:1) %>% select(c(MidPeriod, Sex, px)) %>%
  group_by(MidPeriod, Sex) %>%
  summarise_at(vars(px),prod) %>%
  mutate(q50 = 1-px,
         year5 = MidPeriod - 3) %>%
  ungroup() %>% arrange(Sex, year5) %>%
  select(c(Sex, year5, q50))

wpp.5q0.interpolate <- bind_rows(
  approx(x = seq(1952, 2097, by = 5), y = wpp.5q0 %>% filter(Sex=="Female") %>% .$q50, xout=1952:2097)$y %>%
    as_tibble() %>%
    mutate(q50 = value,
           Sex = "Female",
           year = 1952:2097,
           .keep = "none"),
  
  approx(x = seq(1952, 2097, by = 5), y = wpp.5q0 %>% filter(Sex=="Male") %>% .$q50, xout=1952:2097)$y %>%
    as_tibble() %>%
    mutate(q50 = value,
           Sex = "Male",
           year = 1952:2097,
           .keep = "none")
)

#DDHarmonized smoothed
census_pop_counts <- DDharmonize_validate_PopCounts(locid = ifelse(country=="Cote d'Ivoire", 384, 
                                                                   ifelse(country=="Tanzania",834, country)),       
                                                    times = 1950:2020,
                                                    DataSourceShortName = "DYB") # time frame for censuses to extract from Demographic Yearbook

#####################MIXING DE-FACTO AND DE-JURE HERE
#####################MIXING DE-FACTO AND DE-JURE HERE
ddharm_bf_census_m <- census_pop_counts %>%  
  filter(AgeSpan %in% c(-1, 1), AgeLabel != "Total", ReferencePeriod > 1960, SexID == 1, complete == TRUE) %>%
  select(ReferencePeriod, StatisticalConceptName, AgeStart, AgeLabel, AgeSpan, DataValue, SexID) %>%
  distinct() %>%
  pivot_wider(names_from = ReferencePeriod, values_from = DataValue) %>%
  group_by(AgeStart, AgeLabel, AgeSpan) %>%
  arrange(AgeStart, StatisticalConceptName) %>% ###De-factor first
  select(-c(StatisticalConceptName, SexID)) %>%
  summarise_all(function(y){first(na.omit(y))}) %>%
  select(-AgeSpan) %>%
  ungroup()

ddharm_bf_census_f <- census_pop_counts %>%  
  filter(AgeSpan %in% c(-1, 1), AgeLabel != "Total", ReferencePeriod > 1960, SexID == 2, complete == TRUE) %>%
  select(ReferencePeriod, StatisticalConceptName, AgeStart, AgeLabel, AgeSpan, DataValue, SexID) %>%
  distinct() %>%
  pivot_wider(names_from = ReferencePeriod, values_from = DataValue) %>%
  group_by(AgeStart, AgeLabel, AgeSpan) %>%
  arrange(AgeStart, StatisticalConceptName) %>% ###De-factor first
  select(-c(StatisticalConceptName, SexID)) %>%
  summarise_all(function(y){first(na.omit(y))}) %>%
  select(-AgeSpan) %>%
  ungroup()

ddharm_smoothed <- tibble()

for(i in 3:ncol(ddharm_bf_census_f)){
  dat.f <- ddharm_bf_census_f %>% select(1:2,i) %>% filter(!is.na(ddharm_bf_census_f[[i]])) %>% arrange(AgeStart)
  dat.m <- ddharm_bf_census_m %>% select(1:2,i) %>% filter(!is.na(ddharm_bf_census_m[[i]])) %>% arrange(AgeStart)
  
  stopifnot(length(unique(diff(dat.f$AgeStart))) == 1 | length(unique(diff(dat.m$AgeStart))) == 1)
  
  smoothed.adult <- getSmoothedPop1(popM = dat.m[[3]], popF = dat.f[[3]], Age = dat.m[[1]], EduYrs = 2, subgroup = "adult")
  smoothed.child <- getSmoothedPop1(popM = dat.m[[3]], popF = dat.f[[3]], Age = dat.m[[1]], EduYrs = 2, subgroup = "child")
  
  adult.grad <- as.numeric(str_extract(smoothed.adult$best_smooth_method,"\\s\\d"))
  child.grad <- as.numeric(str_extract(smoothed.child$best_smooth_method,"\\s\\d"))
  
  cat("adult bestGrad5 =",adult.grad,"; child bestGrad5 =",child.grad, "\n")
  
  if(adult.grad >= child.grad){
    ddharm_smoothed <- bind_rows(
      ddharm_smoothed,
      as_tibble(smoothed.adult$popM_smooth) %>% mutate(age = dat.m[[1]], AgeLabel = dat.m[[2]], 
                                                       sex="male", year = as.numeric(names(ddharm_bf_census_f)[i])),
      as_tibble(smoothed.adult$popF_smooth) %>% mutate(age = dat.f[[1]], AgeLabel = dat.f[[2]],
                                                       sex="female", year = as.numeric(names(ddharm_bf_census_m)[i]))
    )} else{
      ddharm_smoothed <- bind_rows(
        ddharm_smoothed,
        as_tibble(smoothed.child$popM_smooth) %>% mutate(age = dat.m[[1]], AgeLabel = dat.m[[2]], 
                                                         sex="male", year = as.numeric(names(ddharm_bf_census_f)[i])),
        as_tibble(smoothed.child$popF_smooth) %>% mutate(age = dat.f[[1]], AgeLabel = dat.f[[2]],
                                                         sex="female", year = as.numeric(names(ddharm_bf_census_m)[i]))
      )
    }
}

ddharm_smoothed_mat <- ddharm_smoothed %>% pivot_wider(names_from = year, values_from = value) %>% arrange(sex, age)

ddharm_census_f_smoothed <- ddharm_smoothed_mat %>% filter(sex=="female") %>% select(-sex)
ddharm_census_m_smoothed <- ddharm_smoothed_mat %>% filter(sex=="male") %>% select(-sex)

ddharm_bf_census_f_oag <- ddharm_census_f_smoothed %>% 
  #rename(age = AgeStart) %>%
  group_by(age) %>% 
  summarise_at(vars(-AgeLabel), function(y){first(na.omit(y))}) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

ddharm_bf_census_m_oag <- ddharm_census_m_smoothed %>% 
  #rename(age = AgeStart) %>%
  group_by(age) %>%
  summarise_at(vars(-AgeLabel), function(y){first(na.omit(y))}) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

##census data 5 year age groups
ddharm_bf_census_m_5 <- census_pop_counts %>%  
  filter(AgeSpan %in% c(-1, 5), AgeLabel != "Total", ReferencePeriod > 1960, SexID == 1, five_year == TRUE) %>%
  select(ReferencePeriod, StatisticalConceptName, AgeStart, AgeLabel, AgeSpan, DataValue, SexID) %>%
  distinct() %>%
  pivot_wider(names_from = ReferencePeriod, values_from = DataValue) %>%
  group_by(AgeStart, AgeLabel, AgeSpan) %>%
  arrange(AgeStart, StatisticalConceptName) %>% ###De-factor first
  select(-c(StatisticalConceptName, SexID)) %>%
  summarise_all(function(y){first(na.omit(y))}) %>%
  select(-AgeSpan) %>%
  ungroup()

ddharm_bf_census_f_5 <- census_pop_counts %>%  
  filter(AgeSpan %in% c(-1, 5), AgeLabel != "Total", ReferencePeriod > 1960, SexID == 2, five_year == TRUE) %>%
  select(ReferencePeriod, StatisticalConceptName, AgeStart, AgeLabel, AgeSpan, DataValue, SexID) %>%
  distinct() %>%
  pivot_wider(names_from = ReferencePeriod, values_from = DataValue) %>%
  group_by(AgeStart, AgeLabel, AgeSpan) %>%
  arrange(AgeStart, StatisticalConceptName) %>% ###De-factor first
  select(-c(StatisticalConceptName, SexID)) %>%
  summarise_all(function(y){first(na.omit(y))}) %>%
  select(-AgeSpan) %>%
  ungroup()

ddharm_smoothed_5 <- tibble()

for(i in 3:ncol(ddharm_bf_census_f_5)){
  dat.f <- ddharm_bf_census_f_5 %>% select(1:2,i) %>% filter(!is.na(ddharm_bf_census_f_5[[i]])) %>% arrange(AgeStart)
  dat.m <- ddharm_bf_census_m_5 %>% select(1:2,i) %>% filter(!is.na(ddharm_bf_census_m_5[[i]])) %>% arrange(AgeStart)
  
  stopifnot(length(unique(diff(dat.f$AgeStart))) == 1 | length(unique(diff(dat.m$AgeStart))) == 1)
  
  smoothed.adult <- getSmoothedPop5(popM = dat.m[[3]], popF = dat.f[[3]], Age = dat.m[[1]], EduYrs = 2, subgroup = "adult")
  smoothed.child <- getSmoothedPop5(popM = dat.m[[3]], popF = dat.f[[3]], Age = dat.m[[1]], EduYrs = 2, subgroup = "child")
  
  adult.grad <- as.numeric(str_extract(smoothed.adult$best_smooth_method,"\\s\\d"))
  child.grad <- as.numeric(str_extract(smoothed.child$best_smooth_method,"\\s\\d"))
  
  cat("adult bestGrad5 =",adult.grad,"; child bestGrad5 =",child.grad, "\n")
  
  ddharm_smoothed_5 <- bind_rows(
    ddharm_smoothed_5,
    as_tibble(DemoTools::smooth_age_5(dat.m[[3]], dat.m[[1]], method="MAV", n=max(adult.grad, child.grad))) %>% mutate(age = dat.m[[1]], AgeLabel = dat.m[[2]], 
                                                                                                                       sex="male", year = as.numeric(names(ddharm_bf_census_f_5)[i])),
    as_tibble(DemoTools::smooth_age_5(dat.f[[3]], dat.f[[1]], method="MAV", n=max(adult.grad, child.grad))) %>% mutate(age = dat.f[[1]], AgeLabel = dat.f[[2]],
                                                                                                                       sex="female", year = as.numeric(names(ddharm_bf_census_m_5)[i]))
  )
}

ddharm_smoothed_mat_5 <- ddharm_smoothed_5 %>% pivot_wider(names_from = year, values_from = value) %>% arrange(sex, age)

ddharm_census_f_smoothed_5 <- ddharm_smoothed_mat_5 %>% filter(sex=="female") %>% select(-sex)
ddharm_census_m_smoothed_5 <- ddharm_smoothed_mat_5 %>% filter(sex=="male") %>% select(-sex)

ddharm_bf_census_f_oag_5 <- ddharm_census_f_smoothed_5 %>%
  group_by(age) %>%
  summarise_at(vars(-AgeLabel), function(y){first(na.omit(y))}) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

ddharm_bf_census_m_oag_5 <- ddharm_census_m_smoothed_5 %>%
  group_by(age) %>%
  summarise_at(vars(-AgeLabel), function(y){first(na.omit(y))}) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

##WPP Pop Estimates
pop.singleyear <- wpp.pop.age.specific %>% filter(Name == country) %>% 
  setNames(c(names(wpp.pop)[1:3], 0:100)) %>%
  reshape2::melt(id.vars=c("Name", "Sex", "Reference")) %>% 
  mutate(year = Reference, 
         value = as.numeric(str_replace_all(value, "\\s", "")) * 1000,
         age = variable) %>%
  select(Sex, year, age, value) %>%
  pivot_wider(values_from = value, names_from = year) %>%
  mutate(age = as.numeric(levels(age))[age])

pop.f.oag <- pop.singleyear  %>%
  filter(Sex=="female") %>%
  select(-Sex) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

pop.m.oag <- pop.singleyear  %>%
  filter(Sex=="male") %>%
  select(-Sex) %>%
  mutate(aggr.age = ifelse(age >= open.age, open.age, age)) %>%
  group_by(aggr.age) %>%
  summarise_at(vars(-age), function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  mutate(age = aggr.age) %>%
  group_by(age) %>%
  summarise_all(function(i){if(all(is.na(i))){NA} else {sum(i,na.rm=T)}}) %>%
  select(-2) 

bf.idx1<-projection_indices(period_start = 1960,
                            #period_end = max(floor(as.numeric(max(grep("\\d+", names(ddharm_bf_census_f), value=TRUE))) / 5)  * 5 + 5, 2015),
                            period_end = 2020,
                            interval = 1,
                            n_ages = n_ages,
                            fx_idx = 16L,
                            n_fx = 35L,
                            n_sexes = 2)

bf.idx5<-projection_indices(period_start = 1960,
                            #period_end = max(floor(as.numeric(max(grep("\\d+", names(ddharm_bf_census_f), value=TRUE))) / 5)  * 5 + 5, 2015),
                            period_end = 2020,
                            interval = 5,
                            n_ages = open.age %/% 5 + 1,
                            fx_idx = 4L,
                            n_fx = 4L,
                            n_sexes = 2)

##WPP fx
fx <- wpp.fx %>% filter(Name == country) %>% reshape2::melt() %>% 
  mutate(year = as.numeric(str_extract(Reference,"\\d{4}")), 
         fx = value/1000,
         age = as.numeric(str_extract(variable,"\\d{2}"))) %>%
  select(year,age, fx)

fx_init.singleyear <-  fx %>% filter(year %in% bf.idx1$periods) %>%
  pivot_wider(names_from=year, values_from=fx) %>% 
  select(-age) %>% as.matrix() %>%
  apply(1, function(i){approx(x=seq(1960, 2015, by = 5)+2, y=i, xout=1960:2020, rule=2)$y}) %>%
  apply(1, function(i){approx(x=seq(15,45,by=5)+2 , y=i, xout=15:49, rule=2)$y}) %>%
  `colnames<-`(1960:2020)

log_fx_mean <- as.vector(log(fx_init.singleyear))

thiele.loghump.prior <- function(h, sex) {
  cat(h,"\n")
  log.m0 <- h - log(1 - 0.5 * exp(h)) + log(0.2)
  if(sex == "male"){
    LQ.mx <- c(log.m0, as.matrix(LQcoef.m[,1:3]) %*% c(1, h, h^2))
  } else if (sex == "female") {
    LQ.mx <- c(log.m0, as.matrix(LQcoef.f[,1:3]) %*% c(1, h, h^2))
  }
  
  #get priors for phi and psi using LQ mx at 0-4 to 10-14
  child.coef <- lm((LQ.mx[2:3]-log.m0) ~ c(5, 10)-1)$coef
  psi <- -child.coef
  
  #get priors for lambda, delta and epsilon using 10-14 to 40-44
  hump.coef <- lm(LQ.mx[3:9] ~  log(seq(12, 42, by = 5)) + I(log(seq(12, 42, by = 5))^2))$coef
  delta <- -hump.coef[3]
  epsilon <- exp(-hump.coef[2] / (2 * hump.coef[3]))
  lambda <- exp(hump.coef[1]+delta*(log(epsilon)^2))
  
  lambda <- ifelse(lambda<1e-5 | lambda>0.015, 8e-3, lambda)
  delta <- ifelse(delta<1e-10, 1e-3, delta)
  epsilon <- ifelse(epsilon>40 | epsilon<10, 25, epsilon)
  
  #get priors for A and B using 65-69 to 90-94
  old.coef <- lm(LQ.mx[14:19] ~ seq(67, 92, by = 5))$coef
  A <- exp(old.coef[1])
  B <- old.coef[2]
  
  thiele.min <- function(par, dat){
    all.age <- seq(2, 92, by = 5)
    par <- exp(par)
    est <- par[1] * exp(-par[2] * (all.age-2)) + par[3] * exp(-par[4]*((log(all.age) - log(par[5]))^2)) + par[6] * exp(par[7] * (all.age-92))
    ess <- mean(sum((log(est[-1]) - dat[-1])^2) + 1e3 * (log(est[1]) - dat[1])^2)
    return(ess)
  }
  nlm <- nlminb(start = log(c(exp(log.m0), psi, 0.02, 2, 22, exp(LQ.mx[19])-2e-3*exp(-0.5*(log(92)-log(22))^2), 0.1)), thiele.min, dat = LQ.mx[1:19], control = list(eval.max = 8000, iter.max = 8000, step.min = 1e-10, step.max = 1e-4))
  stopifnot(nlm$convergence ==0)
  cat(nlm$message,"\n")
  return(setNames(exp(nlm$par), c("phi", "psi", "lambda", "delta", "epsilon", "A", "B")))
}

igme.h.mean.f <- igme.5q0.df %>% filter(Sex=="Female", year %in% bf.idx1$periods) %>% right_join(as_tibble(bf.idx1$periods)%>%mutate(year=value)) %>% .$child.mort %>% log()
h.mean.f <- wpp.5q0.interpolate %>% filter(Sex=="Female", year %in% bf.idx1$periods) %>% .$q50 %>% log() ##Using WPP 5q0 estimates
#thiele.prior.f <- sapply(h.mean.f, thiele.prior, sex="female")
thiele.loghump.prior.f <- sapply(h.mean.f, thiele.loghump.prior, sex="female")

igme.h.mean.m <- igme.5q0.df %>% filter(Sex=="Male", year %in% bf.idx1$periods) %>% right_join(as_tibble(bf.idx1$periods)%>%mutate(year=value)) %>% .$child.mort %>% log()
h.mean.m <- wpp.5q0.interpolate %>% filter(Sex=="Male", year %in% bf.idx1$periods) %>% .$q50 %>% log() ##Using WPP 5q0 estimates
#thiele.prior.m <- sapply(h.mean.m, thiele.prior, sex="male")
thiele.loghump.prior.m <- sapply(h.mean.m, thiele.loghump.prior, sex="male")

thiele_age <- 0.5:97.5

##DHS data cohort smoothed
bf5.smooth <- aggr.mat.cohort.0[[country]] %>%
  filter(period %in% bf.idx1$periods) %>%
  group_by(mm1, tips, DHS, agegr, period) %>%
  summarise_at(vars(pyears, event, pyears2, adjusted), sum) %>%
  ungroup()

bf5.smooth$period <- factor(bf5.smooth$period,levels=bf.idx1$periods)
bf5.smooth$tips <- factor(bf5.smooth$tips,levels=0:14)

dhs.start.age <- 15
dhs.end.age <- 59

bf5.f.no0.smooth <- bf5.smooth %>% filter(mm1=="female", agegr >= dhs.start.age, agegr <= dhs.end.age) %>% arrange(period,tips,agegr)
bf5.m.no0.smooth <- bf5.smooth %>% filter(mm1=="male", agegr >= dhs.start.age, agegr <= dhs.end.age) %>% arrange(period,tips,agegr)

basepop.f <- ifelse(pop.f.oag$`1960`==0, 1, pop.f.oag$'1960')
basepop.m <- ifelse(pop.m.oag$`1960`==0, 1, pop.m.oag$'1960')

data.f <- as.matrix(log(ddharm_bf_census_f_oag[,-1])); data.m <- as.matrix(log(ddharm_bf_census_m_oag[,-1]))
data.f.5 <- as.matrix(log(ddharm_bf_census_f_oag_5[,-1] %>% select(!all_of(colnames(data.f))))); data.m.5 <- as.matrix(log(ddharm_bf_census_m_oag_5[,-1] %>% select(!all_of(colnames(data.f)))))

if(country == "Zimbabwe"){
  data.f <- as.matrix(log(ddharm_bf_census_f_oag[,-(1:2)])); data.m <- as.matrix(log(ddharm_bf_census_m_oag[,-(1:2)]))
  data.f.5 <- as.matrix(log(ddharm_bf_census_f_oag_5[,-(1:2)] %>% select(!all_of(colnames(data.f))))); data.m.5 <- as.matrix(log(ddharm_bf_census_m_oag_5[,-(1:2)] %>% select(!all_of(colnames(data.f)))))
  
}
init_lambda_f <- thiele.loghump.prior.f[3,1]; init_lambda_m <- thiele.loghump.prior.m[3,1]; 
init_delta_f <- thiele.loghump.prior.f[4,1]; init_delta_m <- thiele.loghump.prior.m[4,1]; 
init_epsilon_f <- thiele.loghump.prior.f[5,1]; init_epsilon_m <- thiele.loghump.prior.m[5,1]; 

```

```{r, echo=FALSE}
print("Census Females")
ddharm_bf_census_f_oag
print("Census Females 5-year")
ddharm_bf_census_f_oag_5 %>% select(!all_of(colnames(data.f)))
print("Census Males")
ddharm_bf_census_m_oag
print("Census Males 5-year")
ddharm_bf_census_m_oag_5 %>% select(!all_of(colnames(data.m)))
```

___Thiele log-Normal Hump Spline___
```{r, echo=FALSE}

thiele.f.loghump.oag.RW.ori$message  

thiele.f.loghump.oag.RW.ori$par
```

```{r, include=FALSE}
loghump.models.list <- list("Thiele RW" = thiele.f.loghump.oag.RW.ori)

rmvnorm_sparseprec <- function(n, mean = rep(0, nrow(prec)), prec = diag(lenth(mean))) {
  z = matrix(rnorm(n * length(mean)), ncol = n)
  L_inv = Matrix::Cholesky(prec)
  v <- mean + Matrix::solve(as(L_inv, "pMatrix"), Matrix::solve(Matrix::t(as(L_inv, "Matrix")), z))
  as.matrix(Matrix::t(v))
}  

var.sample <- function(fit, nsample){
  r <- fit$obj$env$random
  par_f <- fit$par.full[-r]
  
  par_r <- fit$par.full[r]
  hess_r <- fit$obj$env$spHess(fit$par.full, random = TRUE)
  smp_r <- rmvnorm_sparseprec(nsample, par_r, hess_r)
  
  smp <- matrix(0, nsample, length(fit$par.full))
  smp[ , r] <- smp_r
  smp[ ,-r] <- matrix(par_f, nsample, length(par_f), byrow = TRUE)
  colnames(smp) <- rep("NA", length(fit$par.full))
  colnames(smp)[r] <- names(par_r)
  colnames(smp)[-r] <- names(par_f)
  smp
}

thiele.var.sim <-  apply(var.sample(thiele.f.loghump.oag.RW.ori, 1000), 1, thiele.f.loghump.oag.RW.ori$obj$report)

```

```{r, include=FALSE}
par.func <- function(x){
  bind_rows(phi = x$mode$phi_f,
            psi = x$mode$psi_f,
            lambda = x$mode$lambda_f,
            delta = x$mode$delta_f,
            epsilon = x$mode$epsilon_f,
            A = x$mode$A_f,
            B = x$mode$B_f) %>%
    mutate(sex="female", period5 = bf.idx1$periods)  %>%
    bind_rows(
      bind_rows(phi = x$mode$phi_m,
                psi = x$mode$psi_m,
                lambda = x$mode$lambda_m,
                delta = x$mode$delta_m,
                epsilon = x$mode$epsilon_m,
                A = x$mode$A_m,
                B = x$mode$B_m) %>%
        mutate(sex="male", period5 = bf.idx1$periods)
    )
}

thiele.par.loghump <- lapply(loghump.models.list, par.func) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  pivot_longer(-c(sex, period5, model)) %>%
  bind_rows(
    thiele.loghump.prior.f %>%
      `colnames<-`(bf.idx1$periods) %>%
      reshape2::melt() %>%
      mutate(sex = "female", model = "Initial Values",
             value = replace(value, Var1=="lambda", init_lambda_f),
             value = replace(value, Var1=="delta", init_delta_f),
             value = replace(value, Var1=="epsilon", init_epsilon_f)) %>%
      select(name = Var1, period5 = Var2, value, model, sex),
    thiele.loghump.prior.m %>%
      `colnames<-`(bf.idx1$periods) %>%
      reshape2::melt() %>%
      mutate(sex = "male", model = "Initial Values",
             value = replace(value, Var1=="lambda", init_lambda_m),
             value = replace(value, Var1=="delta", init_delta_m),
             value = replace(value, Var1=="epsilon", init_epsilon_m)) %>%
      select(name = Var1, period5 = Var2, value, model, sex)
  ) %>%
  mutate(name = fct_inorder(name), model = fct_relevel(model, "Initial Values", "Thiele RW"))

par.var.df <- bind_rows(
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$phi_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "phi"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$psi_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "psi"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$lambda_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "lambda"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$delta_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "delta"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$epsilon_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "epsilon"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$A_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "A"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$B_f}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "female", name = "B"),
  
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$phi_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "phi"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$psi_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "psi"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$lambda_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "lambda"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$delta_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "delta"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$epsilon_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "epsilon"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$A_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "A"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$B_m}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(period5 = bf.idx1$periods, sex = "male", name = "B")
) %>%
  mutate(name = fct_inorder(name))
```
\vspace{12pt}

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Estimated parameters", out.height= "0.7\\paperheight"}
ggplot(thiele.par.loghump) + geom_line(aes(x = period5, y = value, linetype = model, col = sex), lwd = 1.2) +
  geom_ribbon(data = par.var.df, aes(x = period5, ymin = `2.5%`, ymax = `97.5%`,fill=sex),alpha=0.2) + 
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35),
        legend.key.width = unit(2,"cm")) +
  ggtitle(bquote(.(country)~"Estimated Parameters")) +
  scale_linetype_manual(values = c("solid", "dashed", "dotdash")) + 
  facet_wrap(~name, scales="free_y")

```

```{r, include=FALSE}
mx.mat.func <- function(x, hump="normal"){
  age <- 0.5:110.5
  if(hump=="normal"){
    child.mort <- sapply(x$mode$psi_f, function(y){exp(-y*(age-2))}) %*% diag(x$mode$phi_f)
    hump.mort <- sapply(x$mode$epsilon_f, function(y){(y-age)^2}) %*% diag(-x$mode$delta_f) %>% exp() %*% diag(x$mode$lambda_f)
    old.mort <- sapply(x$mode$B_f, function(y){exp(y*(age-92))}) %*% diag(x$mode$A_f)
    child.mort.m <- sapply(x$mode$psi_m, function(y){exp(-y*(age-2))}) %*% diag(x$mode$phi_m)
    hump.mort.m <- sapply(x$mode$epsilon_m, function(y){(y-age)^2}) %*% diag(-x$mode$delta_m) %>% exp() %*% diag(x$mode$lambda_m)
    old.mort.m <- sapply(x$mode$B_m, function(y){exp(y*(age-92))}) %*% diag(x$mode$A_m)
  } else if(hump=="log") {
    child.mort <- sapply(x$mode$psi_f, function(y){exp(-y*(age-2))}) %*% diag(x$mode$phi_f)
    hump.mort <- sapply(x$mode$epsilon_f, function(y){(log(y)-log(age))^2}) %*% diag(-x$mode$delta_f) %>% exp() %*% diag(x$mode$lambda_f)
    old.mort <- sapply(x$mode$B_f, function(y){exp(y*(age-92))}) %*% diag(x$mode$A_f)
    child.mort.m <- sapply(x$mode$psi_m, function(y){exp(-y*(age-2))}) %*% diag(x$mode$phi_m)
    hump.mort.m <- sapply(x$mode$epsilon_m, function(y){(log(y)-log(age))^2}) %*% diag(-x$mode$delta_m) %>% exp() %*% diag(x$mode$lambda_m)
    old.mort.m <- sapply(x$mode$B_m, function(y){exp(y*(age-92))}) %*% diag(x$mode$A_m)
  }
  
  lapply(list(Child = child.mort, Hump = hump.mort, Senescent = old.mort, Total = child.mort + hump.mort + old.mort), function(i){
    i %>%
      `colnames<-`(bf.idx1$periods) %>%  
      `rownames<-`(0:110) %>%
      reshape2::melt()
  })%>% 
    map2(names(.), ~ add_column(.x, stage = rep(.y, nrow(.x)))) %>% 
    bind_rows() %>%
    mutate(sex="female") %>%
    bind_rows(
      lapply(list(Child = child.mort.m, Hump = hump.mort.m, Senescent = old.mort.m, Total = child.mort.m + hump.mort.m + old.mort.m), function(i){
        i %>%
          `colnames<-`(bf.idx1$periods) %>%  
          `rownames<-`(0:110) %>%
          reshape2::melt()
      })%>% 
        map2(names(.), ~ add_column(.x, stage = rep(.y, nrow(.x)))) %>% 
        bind_rows() %>%
        mutate(sex="male")
    )
}

thiele.decomp.loghump <- lapply(loghump.models.list, mx.mat.func, hump="log") %>%
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  bind_rows(
    lapply(
      list(Child = apply(thiele.loghump.prior.f, 2, function(i) {i[1] * exp(-i[2] * (0.5:110.5 - 2))}),
           Hump = apply(thiele.loghump.prior.f, 2, function(i) {init_lambda_f * exp(- init_delta_f * ((log(0.5:110.5) - log(init_epsilon_f))^2))}),
           Senescent = apply(thiele.loghump.prior.f, 2, function(i) {i[6] * exp(i[7] * (0.5:110.5-92))}),
           Total = apply(thiele.loghump.prior.f, 2, function(i) {i[1] * exp(-i[2] * (0.5:110.5 - 2)) + 
               init_lambda_f * exp(- init_delta_f * ((log(0.5:110.5) - log(init_epsilon_f))^2)) +
               i[6] * exp(i[7] * (0.5:110.5 - 92))})
      ), function(i) {
        i %>%
          `colnames<-`(bf.idx1$periods) %>%  
          `rownames<-`(0:110) %>%
          reshape2::melt()
      }) %>% 
      map2(names(.), ~ add_column(.x, stage = rep(.y, nrow(.x)))) %>% 
      bind_rows() %>%
      mutate(sex="female", model = "Initial Values"),
    
    lapply(
      list(Child = apply(thiele.loghump.prior.m, 2, function(i) {i[1] * exp(-i[2] * (0.5:110.5 - 2))}),
           Hump = apply(thiele.loghump.prior.m, 2, function(i) {init_lambda_m * exp(- init_delta_m * ((log((0.5:110.5)) - log(init_epsilon_m))^2))}),
           Senescent = apply(thiele.loghump.prior.m, 2, function(i) {i[6] * exp(i[7] * (0.5:110.5 - 92))}),
           Total = apply(thiele.loghump.prior.m, 2, function(i) {i[1] * exp(-i[2] * (0.5:110.5 - 2)) + 
               init_lambda_m * exp(- init_delta_m * ((log(0.5:110.5) - log(init_epsilon_m))^2)) +
               i[6] * exp(i[7] * (0.5:110.5 - 92))})
      ), function(i) {
        i %>%
          `colnames<-`(bf.idx1$periods) %>%  
          `rownames<-`(0:110) %>%
          reshape2::melt()
      }) %>% 
      map2(names(.), ~ add_column(.x, stage = rep(.y, nrow(.x)))) %>% 
      bind_rows() %>%
      mutate(sex="male", model = "Initial Values") 
  ) %>%
  setNames(c("age", "period", "value", "stage", "sex", "model")) %>%
  mutate(period = as.factor(period),
         age = as.numeric(age),
         stage = fct_relevel(stage, c("Total", "Child", "Hump", "Senescent")),
         model = fct_relevel(model, c("Initial Values", "Thiele RW"))
  )

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Thiele Decomposed", out.height="0.3\\paperheight"}
ggplot(filter(thiele.decomp.loghump, sex=="female")) + geom_line(aes(x = age, y = value, col = period), lwd = 1.2) +
  scale_color_manual(values = colorRampPalette(colors = c("blue", "red"))(bf.idx1$n_periods)) + 
  scale_y_continuous(trans="log", labels = function(x){as.character(round(x, 5))}) +
  theme(text = element_text(size=20),
        strip.text = element_text(size=20)) + 
  ggtitle(paste(country, "Females (log-Normal hump)")) +
  facet_grid(stage~model, scales="free_y", switch = "y")

ggplot(filter(thiele.decomp.loghump, sex=="male")) + geom_line(aes(x = age, y = value, col = period), lwd = 1.2) +
  scale_color_manual(values = colorRampPalette(colors = c("blue", "red"))(bf.idx1$n_periods)) + 
  scale_y_continuous(trans="log", labels = function(x){as.character(round(x, 5))}) +
  theme(text = element_text(size=20),
        strip.text = element_text(size=20)) + 
  ggtitle(paste(country, "Males (log-Normal hump)")) +
  facet_grid(stage~model, scales="free_y", switch = "y")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Estimated $_{5}q_{0}$", out.height="0.3\\paperheight"}
q50.func <- function(x){
    as_tibble(apply(x$mode$mx_mat_f[1:5,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})) %>%
      mutate(sex="female", year = bf.idx1$periods) %>%
      bind_rows(
        as_tibble(apply(x$mode$mx_mat_m[1:5,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})) %>%
          mutate(sex="male", year = bf.idx1$periods)
      )
  }
  
q50.df.loghump <- lapply(loghump.models.list, q50.func) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  bind_rows(
    as_tibble(exp(igme.h.mean.f)) %>% mutate(model="IGME Estimates", year=bf.idx1$periods, variable = NULL, sex = "female"),
    as_tibble(exp(igme.h.mean.m)) %>% mutate(model="IGME Estimates", year=bf.idx1$periods, variable = NULL, sex = "male"),
    
    as_tibble(exp(h.mean.f)) %>% mutate(model="WPP Estimates", year=bf.idx1$periods, variable = NULL, sex = "female"),
    as_tibble(exp(h.mean.m)) %>% mutate(model="WPP Estimates", year=bf.idx1$periods, variable = NULL, sex = "male"),
    
    apply(apply(thiele.loghump.prior.f, 2, function(i) {i[1] * exp(-i[2] * (0.5:4.5-2)) + 
        init_lambda_f * exp(- init_delta_f * ((log(0.5:4.5) - log(init_epsilon_f))^2)) +
        i[6] * exp(i[7] * (0.5:4.5-92))}) %>%
          `colnames<-`(bf.idx1$periods) %>% 
          `rownames<-`(0:4), 2, function(j){1-prod((1-0.5*j)/(1+0.5*j))}) %>%
      as_tibble() %>%
      mutate(sex="female", model = "Initial Values", year = bf.idx1$periods),
    
    apply(apply(thiele.loghump.prior.m, 2, function(i) {i[1] * exp(-i[2] * (0.5:4.5-2)) + 
        init_lambda_m * exp(- init_delta_m * ((0.5:4.5) - log(init_epsilon_m))^2) +
        i[6] * exp(i[7] * (0.5:4.5-92))}) %>%
          `colnames<-`(bf.idx1$periods) %>% 
          `rownames<-`(0:4), 2, function(j){1-prod((1-0.5*j)/(1+0.5*j))}) %>%
      as_tibble() %>%
      mutate(sex="male", model = "Initial Values", year = bf.idx1$periods)
  ) %>%
  mutate(model = fct_relevel(model, "WPP Estimates","IGME Estimates", "Thiele RW"),
         hump = "log-Normal hump")

q50.var.df <- bind_rows(
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(i$mx_mat_f[1:5,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(year = bf.idx1$periods, sex = "female"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(i$mx_mat_m[1:5,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(year = bf.idx1$periods, sex = "male")
)

q50.df.loghump %>% mutate(hump = fct_inorder(hump)) %>%
  ggplot() + geom_line(data=filter(q50.df.loghump, model!="Initial Values"), aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) + ylab(bquote(""[5]*q[0])) +
  geom_point(data = filter(q50.df.loghump, model=="Initial Values"), aes(x = year, y = value, col = sex), size=3) + 
  scale_linetype_manual(values=c("solid", "dotted", "dashed", "dotdash")) +
  geom_ribbon(data = q50.var.df, aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  ggtitle(bquote(.(country)~"Estimated"[5]*q[0])) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Estimated $_{45}q_{15}$", out.height="0.3\\paperheight"}
q4515.func <- function(x){
  as_tibble(apply(x$mode$mx_mat_f[16:59,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})) %>%
    #as_tibble(apply(x$mode$mx_mat_f[4:12,],2,function(x){1-exp(sum(-5*x))})) %>%
    mutate(sex="female", year = bf.idx1$periods) %>%
    bind_rows(
      as_tibble(apply(x$mode$mx_mat_m[16:59,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})) %>%
        #as_tibble(apply(x$mode$mx_mat_m[4:12,],2,function(x){1-exp(sum(-5*x))})) %>%
        mutate(sex="male", year = bf.idx1$periods)
    )
}
wpp.bf.q4515 <- filter(wpp.q4515, Name==country)

gbd.bf.q4515 <- filter(gbd.q4515, location_name == country, year_id %in% bf.idx1$periods, sex_name!="both") %>%
  select(c(4,7,12))

q4515.df.loghump <-  lapply(loghump.models.list, q4515.func) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  bind_rows(
    reshape2::melt(wpp.bf.q4515[,-c(1,3,4)]) %>% 
      mutate(model = "WPP Estimates",
             year = as.numeric(gsub("X|\\.5","",variable)),
             value = value/1000,
             sex = Sex) %>%
      select(-c(variable, Sex)),
    
    gbd.bf.q4515 %>% 
      mutate(model = "GBD Estimates",
             year = year_id-2,
             value = val,
             sex = sex_name) %>%
      select(model:sex),
    
    apply(apply(thiele.loghump.prior.f, 2, function(i) {i[1] * exp(-i[2] * (15.5:59.5-2)) + 
        init_lambda_f * exp(- init_delta_f * ((log(15.5:59.5) - log(init_epsilon_f))^2)) +
        i[6] * exp(i[7] * (15.5:59.5-92))}) %>%
          `colnames<-`(bf.idx1$periods) %>% 
          `rownames<-`(15:59), 2, function(j){1-prod((1-0.5*j)/(1+0.5*j))}) %>%
      as_tibble() %>%
      mutate(sex="female", model = "Initial Values", year = bf.idx1$periods),
    
    apply(apply(thiele.loghump.prior.m, 2, function(i) {i[1] * exp(-i[2] * (15.5:59.5-2)) + 
        init_lambda_m * exp(- init_delta_m * ((15.5:59.5) - log(init_epsilon_m))^2) +
        i[6] * exp(i[7] * (15.5:59.5-92))}) %>%
          `colnames<-`(bf.idx1$periods) %>% 
          `rownames<-`(15:59), 2, function(j){1-prod((1-0.5*j)/(1+0.5*j))}) %>%
      as_tibble() %>%
      mutate(sex="male", model = "Initial Values", year = bf.idx1$periods)
  ) %>%
  mutate(model = fct_relevel(model, c("GBD Estimates","WPP Estimates", "Thiele RW")),
         hump = "log-Normal hump")

q4515.var.df <- bind_rows(
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(i$mx_mat_f[16:59,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(year = bf.idx1$periods, sex = "female"),
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(i$mx_mat_m[16:59,],2,function(x){1-prod((1-0.5*x)/(1+0.5*x))})}), 1, quantile, c(0.025, 0.975))))%>% 
    mutate(year = bf.idx1$periods, sex = "male")
)

q4515.df.loghump %>% 
  ggplot() + geom_line(data = filter(q4515.df.loghump, model!="Initial Values"), aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) + ylab(bquote(""[45]*q[15])) +
  geom_ribbon(data = q4515.var.df, aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  scale_linetype_manual(values=c("solid", "dotted", "dashed", "dotdash")) +
  geom_point(data = filter(q4515.df.loghump, model=="Initial Values"), aes(x = year, y = value, col = sex), size=3) + 
  ggtitle(bquote(.(country)~"Estimated"[45]*q[15])) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35))

```

```{r, include=FALSE}
load("~/more countries final avg sex Rwanda.RData")
skip<-c("Ethiopia","Central African Republic","Comoros","Sao Tome and Principe","Botswana","Cape Verde","Equatorial Guinea","Eritrea","Nigeria (Ondo State)","Ghana","Mauritania","Sudan")
joint.countries<-names(aggr.mat.cohort.0)[!names(aggr.mat.cohort.0)%in%skip]

no.basis = 15

bspline<-function (x,k,i,m=2) {
  if (m==-1) {basis<-as.numeric(x<k[i+1] & x>=k[i])} else {
    z0<-(x-k[i])/(k[i+m+1]-k[i])
    z1<-(k[i+m+2]-x)/(k[i+m+2]-k[i+1])
    basis<-z0*bspline(x,k,i,m-1)+z1*bspline(x,k,i+1,m-1) }
  basis
}

all.list<-function(x,age.start,age.end,year.start,year.end){
  no.basis=no.basis
  knots<-seq(0,1,length=no.basis-2)
  dk<-knots[2]-knots[1]	
  knots<-c(knots[1]-dk*(3:1),knots,knots[no.basis-2]+dk*(1:3))
  age<-seq(0,1,length=age.end-age.start+1)
  year<-seq(0,1,length=year.end-year.start+1)
  
  A.age<-c()
  for(j in 1:no.basis) {
    A.age<-cbind(A.age,bspline(age,knots,j))
  }
  
  A.year<-c()
  for(j in 1:no.basis) {
    A.year<-cbind(A.year,bspline(year,knots,j))
  }
  
  te.spline<-A.year%x%A.age
  
  ind<-function(x){
    aggr.mat.reduced<-x
    data.mat.m<-aggr.mat.reduced[aggr.mat.reduced$mm1=="male" & aggr.mat.reduced$agegr %in% age.start:age.end & aggr.mat.reduced$period %in% year.start:year.end,c(7,5,3,2,4)]
    data.mat.f<-aggr.mat.reduced[aggr.mat.reduced$mm1=="female" & aggr.mat.reduced$agegr %in% age.start:age.end & aggr.mat.reduced$period %in% year.start:year.end,c(7,5,3,2,4)]
    
    age.start.col<-min(which(A.age[min(data.mat.m[,3])-age.start+1,]!=0))
    age.end.col<-max(which(A.age[max(data.mat.m[,3])-age.start+1,]!=0))
    year.start.col<-min(which(A.year[min(data.mat.m[,4])-year.start+1,]!=0))
    year.end.col<-max(which(A.year[max(data.mat.m[,4])-year.start+1,]!=0))
    age.start<-min(data.mat.m[,3])
    age.end<-max(data.mat.m[,3])
    year.start<-min(data.mat.m[,4])
    year.end<-max(data.mat.m[,4])
    tp<-max(data.mat.m[,5],data.mat.f[,5])
    
    ind.place<-c(age.start.col,age.end.col,year.start.col,year.end.col,age.start,age.end,year.start,year.end,tp)
    names(ind.place)<-c("age.start.col", "age.end.col","year.start.col","year.end.col","age.start","age.end","year.start","year.end","tp")
    ind.place
  }  
  
  
  everything.func<-function(i){
    age.seq<-as.numeric(ind.list[[i]][["age.start"]]:ind.list[[i]][["age.end"]])
    year.seq<-as.numeric(ind.list[[i]][["year.start"]]:ind.list[[i]][["year.end"]])
    
    age.m<-A.age[age.seq-age.start+1,]%*%joint.countries.age.m[[i]]
    age.f<-A.age[age.seq-age.start+1,]%*%joint.countries.age.f[[i]]
    time.m<-A.year[year.seq-year.start+1,]%*%joint.countries.time.m[[i]]
    time.f<-A.year[year.seq-year.start+1,]%*%joint.countries.time.f[[i]]
    agetime.m<-matrix(te.spline[age.seq-age.start+1+rep((age.end-age.start+1)*(year.seq-year.start),each=length(age.seq)),]%*%joint.countries.2d.m[[i]],length(age.seq),length(year.seq))
    agetime.f<-matrix(te.spline[age.seq-age.start+1+rep((age.end-age.start+1)*(year.seq-year.start),each=length(age.seq)),]%*%joint.countries.2d.f[[i]],length(age.seq),length(year.seq))
    
    mort.m<-joint.countries.avg.m[[i]]+t(apply(apply(agetime.m,2,function(x){x+age.m}),1,function(x){x+time.m}))
    mort.f<-joint.countries.avg.f[[i]]+t(apply(apply(agetime.f,2,function(x){x+age.f}),1,function(x){x+time.f}))
    rownames(age.m)<-rownames(age.f)<-rownames(agetime.m)<-rownames(agetime.f)<-rownames(mort.m)<-rownames(mort.f)<-age.seq
    rownames(time.m)<-rownames(time.f)<-colnames(agetime.m)<-colnames(agetime.f)<-colnames(mort.m)<-colnames(mort.f)<-year.seq
    
    
    if(i=="Rwanda"){
      mort.m[,4:6]<-mort.m[,4:6]+matrix(rep.par.list$rwanda_geno_m,56,3,byrow=T)
      mort.f[,4:6]<-mort.f[,4:6]+matrix(rep.par.list$rwanda_geno_f,56,3,byrow=T)
    }
    
    tips<-joint.countries.tp.c[[i]]+tp.common
    
    list(tp=tips,avg.m=joint.countries.avg.m[[i]],avg.f=joint.countries.avg.f[[i]],age.m=age.m,age.f=age.f,time.m=time.m,time.f=time.f,agetime.m=agetime.m,agetime.f=agetime.f,mort.m=mort.m,mort.f=mort.f)
  }
  
  ind.list<-lapply(aggr.mat.cohort.0[joint.countries],ind)
  rep.par.list<-split(unname(x$env$last.par.best),names(x$env$last.par.best))
  joint.countries.avg.m<-split(rep.par.list$avg_m,joint.countries)
  joint.countries.avg.f<-split(rep.par.list$avg_f,joint.countries)
  joint.countries.age.m<-split(rep.par.list$spline_params_m_age,rep(joint.countries,each=no.basis))
  joint.countries.age.f<-split(rep.par.list$spline_params_f_age,rep(joint.countries,each=no.basis))
  joint.countries.time.m<-split(rep.par.list$spline_params_m_time,rep(joint.countries,each=no.basis))
  joint.countries.time.f<-split(rep.par.list$spline_params_f_time,rep(joint.countries,each=no.basis))
  joint.countries.2d.m<-split(rep.par.list$spline_params_m_2d,rep(joint.countries,each=no.basis*no.basis))
  joint.countries.2d.f<-split(rep.par.list$spline_params_f_2d,rep(joint.countries,each=no.basis*no.basis))
  
  joint.countries.tp.c<-split(rep.par.list$tips_params,rep(joint.countries,each=length(rep.par.list$tips_params_common)))
  tp.common<-rep.par.list$tips_params_common
  tp.common[6]<-tp.common[6]+rep.par.list$tp_common_5
  tp.common[11]<-tp.common[11]+rep.par.list$tp_common_10
  
  
  setNames(lapply(joint.countries,everything.func),joint.countries)
}

more.countries.avg<-all.list(tmb.full.joint.common,age.start=10,age.end=65,year.start=1990,year.end=2017)

for(i in 1:length(more.countries.avg)){
  more.countries.avg[[i]]$avg.m<-more.countries.avg[[i]]$avg.m+unname(tmb.full.joint.common$env$last.par.best["avg_common_m"])
  more.countries.avg[[i]]$avg.f<-more.countries.avg[[i]]$avg.f+unname(tmb.full.joint.common$env$last.par.best["avg_common_f"])
  more.countries.avg[[i]]$mort.m<-more.countries.avg[[i]]$mort.m+unname(tmb.full.joint.common$env$last.par.best["avg_common_m"])
  more.countries.avg[[i]]$mort.f<-more.countries.avg[[i]]$mort.f+unname(tmb.full.joint.common$env$last.par.best["avg_common_f"])
}

thiele.loghump <- lapply(loghump.models.list, function(y){y$mode$mx_mat_f %>%
    `colnames<-`(bf.idx1$periods) %>%  
    `rownames<-`(thiele_age - 0.5) %>%
    reshape2::melt()}) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  setNames(c("age", "period", "value", "model")) %>%
  mutate(sex = "female") %>%
  bind_rows(
    reshape2::melt(more.countries.avg[[country]]$mort.f) %>% 
      mutate(value = exp(value),
             model = "Spline average",
             sex = "female",
             age = Var1, 
             period = Var2,
             .keep ="none"
             )
  ) %>%
  bind_rows(
    lapply(loghump.models.list, function(y){y$mode$mx_mat_m %>%
        `colnames<-`(bf.idx1$periods) %>%  
        `rownames<-`(thiele_age - 0.5) %>%
        reshape2::melt()}) %>% 
      map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
      bind_rows() %>%
      setNames(c("age", "period", "value", "model")) %>%
      mutate(sex = "male") %>%
      bind_rows(
        reshape2::melt(more.countries.avg[[country]]$mort.m) %>% 
          mutate(value = exp(value),
                 model = "Spline average",
                 sex = "male",
                 age = Var1, 
                 period = Var2,
                 .keep ="none"
          )
      )
  ) %>%
  mutate(model = str_wrap(model, 20),
         hump = "log-Normal hump")

DHS.plot <- bf5.f.no0.smooth %>% mutate(value = adjusted / pyears2, period = as.numeric(levels(period)[period])) %>%
  select(tips, agegr, period, value) %>%
  mutate(sex = "female",
         age = agegr) %>%
  bind_rows(
    bf5.m.no0.smooth %>% mutate(value = adjusted / pyears2, period = as.numeric(levels(period)[period])) %>%
      select(tips, agegr, period, value) %>%
      mutate(sex = "male",
             age = agegr) 
  )

thiele.f <- bind_rows(filter(thiele.loghump, sex == "female")) %>% mutate(model = fct_relevel(model, "Spline average", "Thiele RW"))
thiele.m <- bind_rows(filter(thiele.loghump, sex == "male")) %>% mutate(model = fct_relevel(model, "Spline average", "Thiele RW"))
DHS.plot.f <- filter(DHS.plot, sex == "female")
DHS.plot.m <- filter(DHS.plot, sex == "male")

mx.var.df.f <- as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$mx_mat_f}), 1, quantile, c(0.025, 0.975)))) %>%
  mutate(sex = "female",
         age = rep(thiele_age - 0.5, bf.idx1$n_periods),
         period = rep(bf.idx1$periods, each = length(thiele_age)))

mx.var.df.m <- as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$mx_mat_m}), 1, quantile, c(0.025, 0.975)))) %>%
  mutate(sex = "male",
         age = rep(thiele_age - 0.5, bf.idx1$n_periods),
         period = rep(bf.idx1$periods, each = length(thiele_age)))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Mortality Schedules", out.height="0.8\\paperheight", out.width="0.7\\paperwidth", fig.asp = 1.2}

ggplot(thiele.f %>% filter(age %in% 0:70, hump=="log-Normal hump")) + geom_line(aes(x = age, y = value, col=model), lwd=1.2, linetype = 2) +
  geom_line(data = filter(thiele.f, model == "Spline average"), aes(x = age, y = value, col = model), lwd=1.2, linetype=1) +
  geom_point(data = filter(DHS.plot.f, value!=0), aes(x = age, y = value, shape = tips), alpha = 0) + 
  geom_point(data = filter(DHS.plot.f, value!=0, tips %in% 1:3), aes(x = age, y = value, shape = tips), size=2, stroke=1) +
  geom_point(data = filter(DHS.plot.f, value!=0, !tips %in% 1:3), aes(x = age, y = value, shape = tips), size=1, alpha = 0.3) +
  geom_ribbon(data = mx.var.df.f, aes(x = age, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 4) +
  scale_shape_manual(values = 0:14) +
  scale_y_continuous(trans = "log", labels = function(x){as.character(round(x,3))}) +
  ggtitle(paste(country, "Females (log-Normal hump)")) + ylab(bquote(""[5]*m[x])) + xlab("5-year age groups") +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap(~period)

ggplot(thiele.m %>% filter(age %in% 0:70, hump == "log-Normal hump")) + geom_line(aes(x = age, y = value, col=model), lwd=1.2, linetype = 2) +
  geom_line(data = filter(thiele.m, model == "Spline average"), aes(x = age, y = value, col = model), lwd=1.2, linetype=1)+
  geom_point(data = filter(DHS.plot.m, value!=0), aes(x = age, y = value, shape = tips), alpha = 0) + 
  geom_point(data = filter(DHS.plot.m, value!=0, tips %in% 1:3), aes(x = age, y = value, shape = tips), size=2, stroke=1) +
  geom_point(data = filter(DHS.plot.m, value!=0, !tips %in% 1:3), aes(x = age, y = value, shape = tips), size=1, alpha = 0.3) +
  geom_ribbon(data = mx.var.df.m, aes(x = age, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 4) +
  scale_shape_manual(values = 0:14) +
  scale_y_continuous(trans = "log", labels = function(x){as.character(round(x,3))}) +
  facet_wrap(~period) + 
  ggtitle(paste(country, "Males (log-Normal hump)")) + ylab(bquote(""[5]*m[x])) + xlab("5-year age groups") +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35))

ggplot(bind_rows(thiele.f, thiele.m) %>% filter(age %in% seq(0,70, by = 5), hump=="log-Normal hump")) + geom_line(aes(x = period, y = value, col=sex, linetype=model), lwd=1.2) +
  scale_y_continuous(trans = "log", labels = function(x){as.character(round(x,3))}) +
  geom_ribbon(data = bind_rows(mx.var.df.m, mx.var.df.f) %>% filter(age %in% seq(0,70, by = 5)), aes(x = period, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  ggtitle(paste(country, "Estimate Mortality Schedules")) + ylab(bquote(""[5]*m[x])) + xlab("5-year age groups") +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap(~age)
```

```{r, include=FALSE}
mf5 <- projection_model_frames(bf.idx1)
get.pop<- function(x){
  pop.mat <- matrix(x$mode$population_f, bf.idx1$n_ages, bf.idx1$n_periods+1)
  pop.mat.m <- matrix(x$mode$population_m, bf.idx1$n_ages, bf.idx1$n_periods+1)
  rownames(pop.mat) <-  rownames(pop.mat.m) <- c(bf.idx1$ages)
  colnames(pop.mat) <- colnames(pop.mat.m) <- bf.idx1$periods_out
  bind_rows(
    reshape2::melt(pop.mat) %>% mutate(sex="female"),
    reshape2::melt(pop.mat.m) %>% mutate(sex="male")
  ) %>%
    select(age = Var1, year = Var2, value = value, sex)
}

pop.df <- lapply(loghump.models.list, get.pop) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  bind_rows(
    bind_rows(ddharm_bf_census_f_oag %>% mutate(age = c(ddharm_bf_census_f_oag$age), sex = "female"),
              ddharm_bf_census_m_oag %>% mutate(age = c(ddharm_bf_census_m_oag$age), sex = "male")
    ) %>%
      pivot_longer(!age & !sex) %>% mutate(year=as.numeric(name), name=NULL, model="UNPD Census smoothed"),
    
    bind_rows(mutate(pop.f.oag[,-(1:3)], age = pop.f.oag$age, sex = "female"),
              mutate(pop.m.oag[,-(1:3)], age = pop.m.oag$age, sex = "male")
    )%>%
      pivot_longer(!age & !sex) %>% mutate(year=as.numeric(name), name=NULL, model="WPP Estimates")
  ) %>%
  mutate(cohort = year - age,
         model = fct_relevel(model, c("UNPD Census smoothed", "WPP Estimates", "Thiele RW")),
         hump = "log-Normal hump"
  )

pop.var.df <- bind_rows(
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$population_f}), 1, quantile, c(0.025, 0.975))))%>%
    mutate(sex = "female",
           age = rep(bf.idx1$ages, bf.idx1$n_periods + 1),
           year = rep(bf.idx1$periods_out, each = bf.idx1$n_ages),
           period5 = sprintf("%d-%d", year, year + 4)),
  
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$population_m}), 1, quantile, c(0.025, 0.975))))%>%
    mutate(sex = "male",
           age = rep(bf.idx1$ages, bf.idx1$n_periods + 1),
           year = rep(bf.idx1$periods_out, each = bf.idx1$n_ages),
           period5 = sprintf("%d-%d", year, year + 4))
)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Population", out.height="0.3\\paperheight"}

pop.df %>% filter(year %in% c(1960, colnames(data.f)), !model %in% c("UNPD Census smoothed", "WPP Estimates")) %>%
  ggplot() + geom_line(aes(x = age, y = value, col = sex, linetype=model), lwd = 1) +
  geom_point(data = pop.df %>% filter(year == 1960, model %in% c("WPP Estimates")),
             aes(x = age, y = value, pch = model, col = sex), size=1.5) +
  geom_point(data = pop.df %>% filter(year %in% c(1960, colnames(data.f)), model %in% c("UNPD Census smoothed")),
             aes(x = age, y = value, pch = model, col = sex), size=1.5) +
  scale_shape_manual(values = c(16,0,3)) +
  geom_ribbon(data=pop.var.df %>% filter(year %in% c(1960, colnames(data.f))), 
              aes(x = age, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha = 0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25)) + ylab("Population counts") + 
  scale_y_continuous(label = function(x) format(x, scientific = TRUE)) +
  ggtitle(country) +
  facet_grid(year~sex, scale="free_y", switch = "y")
  #facet_grid_paginate(year~sex, scale="free_y", switch = "y", nrow = 3, ncol = 2, page=1)

pop.df %>% filter(!model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) +
  geom_point(data = pop.df %>% filter(year %in% c(1960, colnames(data.f)), model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)),
             aes(x = year, y = value, pch = model, col = sex), size=3) +
  scale_shape_manual(values = c(0, 16, 3)) +
  geom_ribbon(data= pop.var.df %>% filter(age %in% seq(0, 70, by = 5)), 
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha = 0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25)) +
  scale_y_continuous(label = function(x) format(x, scientific = TRUE)) +
  ggtitle(country) +
  facet_grid_paginate(age~sex, scale="free", switch="y", nrow = 4, ncol = 2, page=1)

pop.df %>% filter(!model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) +
  geom_point(data = pop.df %>% filter(year %in% c(1960, colnames(data.f)), model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)),
             aes(x = year, y = value, pch = model, col = sex), size=3) +
  scale_shape_manual(values = c(0, 16, 3)) +
  geom_ribbon(data= pop.var.df %>% filter(age %in% seq(0, 70, by = 5)), 
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha = 0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25)) +
  scale_y_continuous(label = function(x) format(x, scientific = TRUE)) +
  ggtitle(country) +
  facet_grid_paginate(age~sex, scale="free", switch="y", nrow = 4, ncol = 2, page=2)


pop.df %>% filter(!model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) +
  geom_point(data = pop.df %>% filter(year %in% c(1960, colnames(data.f)), model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)),
             aes(x = year, y = value, pch = model, col = sex), size=3) +
  scale_shape_manual(values = c(0, 16, 3)) +
  geom_ribbon(data= pop.var.df %>% filter(age %in% seq(0, 70, by = 5)), 
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha = 0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25)) +
  scale_y_continuous(label = function(x) format(x, scientific = TRUE)) +
  ggtitle(country) +
  facet_grid_paginate(age~sex, scale="free", switch="y", nrow = 4, ncol = 2, page=3)

pop.df %>% filter(!model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = value, col = sex, linetype = model), lwd = 1.2) +
  geom_point(data = pop.df %>% filter(year %in% c(1960, colnames(data.f)), model %in% c("UNPD Census smoothed", "WPP Estimates"), age %in% seq(0, 70, by = 5)),
             aes(x = year, y = value, pch = model, col = sex), size=3) +
  scale_shape_manual(values = c(0, 16, 3)) +
  geom_ribbon(data= pop.var.df %>% filter(age %in% seq(0, 70, by = 5)), 
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha = 0.2) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25)) +
  scale_y_continuous(label = function(x) format(x, scientific = TRUE)) +
  ggtitle(country) +
  facet_grid_paginate(age~sex, scale="free", switch="y", nrow = 4, ncol = 2, page=4)

```

```{r, include=FALSE}

#migration####
get.mig<- function(x){
  pop.mat <- matrix(x$mode$migrations_f, bf.idx1$n_ages, bf.idx1$n_periods)
  pop.mat.m <- matrix(x$mode$migrations_m, bf.idx1$n_ages, bf.idx1$n_periods)
  rownames(pop.mat) <- rownames(pop.mat.m) <- c(bf.idx1$ages)
  colnames(pop.mat) <- colnames(pop.mat.m) <- bf.idx1$periods
  bind_rows(reshape2::melt(pop.mat) %>% mutate(sex = "female"),
            reshape2::melt(pop.mat.m) %>% mutate(sex = "male")
  ) %>% select(age = Var1, year = Var2, mig = value, sex)
}

mig.df <- lapply(loghump.models.list, get.mig) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  mutate(hump = "log-Normal hump")

mig.var.df <- bind_rows(
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$migrations_f/i$population_f[1:(bf.idx1$n_ages*bf.idx1$n_periods)]}), 1, quantile, c(0.025, 0.975)))) %>%
    mutate(sex = "female",
           age = rep(bf.idx1$ages, bf.idx1$n_periods),
           year = rep(bf.idx1$periods, each = bf.idx1$n_ages),
           period5 = sprintf("%d-%d", year, year + 4)),
  
  as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$migrations_m/i$population_m[1:(bf.idx1$n_ages*bf.idx1$n_periods)]}), 1, quantile, c(0.025, 0.975)))) %>%
    mutate(sex = "male",
           age = rep(bf.idx1$ages, bf.idx1$n_periods),
           year = rep(bf.idx1$periods, each = bf.idx1$n_ages),
           period5 = sprintf("%d-%d", year, year + 4))
) %>%
  mutate(cohort = year - age)
```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.cap = "Migration", out.height="0.3\\paperheight"}

inner_join(mig.df, pop.df) %>% mutate(gx = mig/value, model = fct_relevel(model, "Thiele RW")) %>%
  filter(year %in% c(1960, 1975, 1985, 1995, 2005, 2015)) %>%
  ggplot() + geom_line(aes(x = age, y = gx, col = sex, linetype=model), lwd = 1.2) +
  geom_ribbon(data = mig.var.df %>% filter(year %in% c(1960, 1975, 1985, 1995, 2005, 2015)),
              aes(x = age, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  ggtitle(paste(country,"Estimated migration Proportions")) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap_paginate(~year, nrow=3, ncol=2, page=1)

inner_join(mig.df, pop.df) %>% mutate(gx = mig/value, model = fct_relevel(model, "Thiele RW")) %>% filter(age %in% seq(0,70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = gx, col = sex, linetype=model), lwd = 1.2) +
  geom_ribbon(data = mig.var.df %>% filter(age %in% seq(0,70, by = 5)),
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  ggtitle(paste(country,"Estimated migration Proportions")) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap_paginate(~age, nrow=3, ncol=3, page=1)

inner_join(mig.df, pop.df) %>% mutate(gx = mig/value, model = fct_relevel(model, "Thiele RW")) %>% filter(age %in% seq(0,70, by = 5)) %>%
  ggplot() + geom_line(aes(x = year, y = gx, col = sex, linetype=model), lwd = 1.2) +
  geom_ribbon(data = mig.var.df %>% filter(age %in% seq(0,70, by = 5)),
              aes(x = year, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  ggtitle(paste(country,"Estimated migration Proportions")) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap_paginate(~age, nrow=3, ncol=3, page=2)

cohort.label <- paste("Cohort born in", unique(pop.df$cohort))
names(cohort.label) <- unique(pop.df$cohort)

inner_join(mig.df, pop.df) %>% mutate(gx = mig/value, model = fct_relevel(model, "Thiele RW")) %>% filter(cohort %in% seq(1945, 1970, by = 5)) %>%
  ggplot() + geom_line(aes(x = age, y = gx, col = sex, linetype = model), lwd = 1.2) +
  geom_ribbon(data = mig.var.df %>% filter(cohort %in% seq(1945, 1970, by = 5)),
              aes(x = age, ymin = `2.5%`, ymax = `97.5%`, fill = sex), alpha=0.2) +
  ggtitle(paste(country,"Estimated migration Proportions")) +
  scale_color_manual(values = c("red", "blue")) +
  scale_fill_manual(values = c("red", "blue")) +
  theme(text = element_text(size=25), legend.key.size = unit(1.5,"cm"), strip.text = element_text(size=30),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35)) +
  facet_wrap_paginate(~cohort, nrow=3, ncol=2, page = 1, labeller = labeller(cohort = cohort.label))

```


```{r, include=FALSE}
#fertility####
get.fert<- function(x){
  pop.mat <- matrix(x$mode$fx, bf.idx1$n_fx, bf.idx1$n_periods)
  rownames(pop.mat) <- c(bf.idx1$fertility_ages)
  colnames(pop.mat) <- bf.idx1$periods
  reshape2::melt(pop.mat) %>% select(age = Var1, year = Var2, value = value)
}

fx.df <- lapply(loghump.models.list, get.fert) %>% 
  map2(names(.), ~ add_column(.x, model = rep(.y, nrow(.x)))) %>% 
  bind_rows() %>%
  bind_rows(
    reshape2::melt(fx_init.singleyear %>% `rownames<-`(bf.idx1$fertility_ages)) %>%
      select(age = Var1, year = Var2, value = value) %>%
      mutate(model = "Initial Values")
  ) %>%
  mutate(hump = "log-Normal hump",
         model = fct_relevel(model, c("Initial Values", "Thiele RW"))) 

fx.var.df <- as_tibble(t(apply(sapply(thiele.var.sim, function(i){i$fx}), 1, quantile, c(0.025, 0.975)))) %>%
  mutate(age = rep(bf.idx1$fertility_ages, bf.idx1$n_periods),
         year = rep(bf.idx1$periods, each = bf.idx1$n_fx),
         period5 = sprintf("%d-%d", year, year + 4))


tfr.df <- fx.df %>%
  group_by(year, model, hump) %>%
  summarise_at(vars(value), function(i){sum(i)})

tfr.var.df <- as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(matrix(i$fx, bf.idx1$n_fx, bf.idx1$n_periods), 2, function(j){sum(j)})}), 1, quantile, c(0.025, 0.975)))) %>%
  mutate(year = bf.idx1$periods)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Total Fertility", out.height="0.3\\paperheight"}

tfr.df %>% filter(model != "Initial Values") %>%
  ggplot() + geom_line(aes(x = year, y = value, col = model), lwd = 1.2) +
  geom_point(data = filter(tfr.df, model=="Initial Values"), aes(x = year, y = value), size = 3) +
  geom_ribbon(data = tfr.var.df, aes(x = year, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 2) +
  ggtitle(paste(country, "Estimated Total Fertility Rates")) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35),
        legend.key.width = unit(2,"cm")) 
```

```{r, include=FALSE}
mfr.df <- fx.df %>%
  group_by(year, model, hump) %>%
  summarise_at(vars(value), function(i){sum(i *15:49)/ sum(i)})
  
mfr.var.df <- as_tibble(t(apply(sapply(thiele.var.sim, function(i){apply(matrix(i$fx, bf.idx1$n_fx, bf.idx1$n_periods), 2, function(j){sum(j*15:49)/sum(j)})}), 1, quantile, c(0.025, 0.975)))) %>%
  mutate(year = bf.idx1$periods)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Mean age at births", out.height="0.3\\paperheight"}
mfr.df %>% filter(model != "Initial Values") %>%
  ggplot() + geom_line(aes(x = year, y = value, col = model), lwd = 1.2) +
  geom_point(data = filter(mfr.df, model=="Initial Values"), aes(x = year, y = value), size = 3) +
  geom_ribbon(data = mfr.var.df, aes(x = year, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 2) +
  ggtitle(paste(country, "Estimated Total Fertility Rates")) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35),
        legend.key.width = unit(2,"cm")) 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Fertility", out.height="0.3\\paperheight"}
fx.df %>% filter(model != "Initial Values", year %in% c(1960, 1975, 1985, 1995, 2005, 2015)) %>%
  ggplot() + geom_line(aes(x = age, y = value, col = model), lwd = 1.2) +
  geom_point(data = filter(fx.df, model=="Initial Values", year %in% c(1960, 1975, 1985, 1995, 2005, 2015)), aes(x = age, y = value), size = 3) +
  geom_ribbon(data = filter(fx.var.df, year %in% c(1960, 1975, 1985, 1995, 2005, 2015)), aes(x = age, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 2) +
  ggtitle(paste(country, "Estimated Fertility Rates")) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35),
        legend.key.width = unit(2,"cm")) +
  facet_wrap_paginate(~year, nrow = 3, ncol = 2, page=1)

fx.df %>% filter(model != "Initial Values", age %in% c(15,25,35,45)) %>%
  ggplot() + geom_line(aes(x = year, y = value, col = model), lwd = 1.2) +
  geom_point(data = filter(fx.df, model=="Initial Values", age %in% c(15,25,35,45)), aes(x = year, y = value), size = 3) +
  geom_ribbon(data = filter(fx.var.df, age %in% c(15,25,35,45)), aes(x = year, ymin = `2.5%`, ymax = `97.5%`), alpha=0.2, fill = 2) +
  theme(text = element_text(size=25),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 35),
        legend.key.width = unit(2,"cm")) +
  facet_wrap_paginate(~age, scale="free_y", nrow = 2, ncol = 2, page=1)

```
